INSERT INTO mascot(mascot_name, description, team_name) VALUES 
('Big_Red', 'a_cardinal_bird', 'cardinals'),
('Freddie_Falcon', 'a_falcon_bird', 'falcons'),
('Poe', 'a_raven_bird', 'ravens'),
('Billy_Buffalo', 'a_buffalo', 'bills'),
('Sir_Purr', 'a_panther', 'panthers'),
('Staley_Da_Bear', 'a_bear', 'bears'),
('Who_Dey', 'a_bengal_tiger', 'bengals'),
('Chomps', 'a_brown_bulldog', 'browns'),
('Rowdy', 'a_cowboy', 'cowboys'),
('Thunder_II', 'a_bronco_horse', 'broncos'),
('Roary', 'a_lion', 'lions'),
('Packers_Person', 'a_packer_person', 'packers'),
('Toro', 'a_bull', 'texans'),
('Blue', 'a_colt horse', 'colts'),
('Jaxson_de_Ville', 'a_jaguar', 'jaguars'),
('K_C_Wolf', 'a_wolf', 'chiefs'),
('Boltman', 'a_lightning_bolt', 'chargers'),
('Rampage', 'a_ram', 'rams'),
('T_D', 'a_dolphin', 'dolphins'),
('Viktor_the_Viking', 'a_viking', 'vikings'),
('Pat_Patriot', 'a_minuteman', 'patriots'),
('Gumbo', 'a_saint', 'saints'),
('G-Man', 'a_giant', 'giants'),
('Fireman_Ed', 'a_jet', 'jets'),
('Raider_Rusher', 'a_raider person', 'raiders'),
('Swoop', 'an_eagle', 'eagles'),
('Steely_McBeam', 'a_steelworker', 'steelers'),
('Sourdough_Sam', 'a_gold_miner', '49ers'),
('Blitz', 'a_seahawk_bird', 'seahawks'),
('Captain_Fear', 'a_pirate', 'buccaneers'),
('T-Rac', 'a_titan', 'titans'),
('Major_Tuddy', 'a_hog', 'commanders');
