INSERT INTO team(name, city, division, conference, sb_wins, stadium, record) VALUES 

('cardinals', 'phoenix', 'nfc_west', 'nfc', 0, 'state_farm_stadium', '4-7'),
('falcons', 'atlanta', 'nfc_south', 'nfc', 0, 'mercedes-benz_stadium', '7-10'),
('ravens', 'baltimore', 'afc_north', 'afc', 2, 'm&t_bank_stadium', '10-7'),
('bills', 'buffalo', 'afc_east', 'afc', 0, 'highmark_stadium', '13-3'),
('panthers', 'charlotte', 'nfc_south', 'nfc', 0, 'bank_of_america_stadium', '7-10'),
('bears', 'chicago', 'nfc_north', 'nfc', 1, 'soldier_field', '3-14'),
('bengals', 'cincinnati', 'afc_north', 'afc', 0, 'paul_brown_stadium', '12-4'),
('browns', 'cleveland', 'afc_north', 'afc', 0, 'firstenergy_stadium', '7-10'),
('cowboys', 'dallas', 'nfc_east', 'nfc', 5, 'at&t_stadium', '12-5'),
('broncos', 'denver', 'afc_west', 'afc', 3, 'mile_high_statidum', '5-12'),
('lions', 'detroit', 'nfc_north', 'nfc', 0, 'ford_field', '9-8'),
('packers', 'green_bay', 'nfc_north', 'nfc', 4, 'lambeau_field', '8-9'),
('texans', 'houston', 'afc_south', 'afc', 0, 'nrg_stadium', '3-13-1'),
('colts', 'indianapolis', 'afc_south', 'afc', 2, 'lucas_oil_stadium', '4-12-1'),
('jaguars', 'jacksonville', 'afc_south', 'afc', 0, 'tiaa_bank_field', '9-8'),
('chiefs', 'kansas_city', 'afc_west', 'afc', 3, 'arrowhead_stadium', '14-3'),
('raiders', 'las_vegas', 'afc_west', 'afc', 3, 'allegiant_stadium', '6-11'),
('chargers', 'los_angeles', 'afc_west', 'afc', 0, 'sofi_stadium', '10-7'),
('rams', 'los_angeles', 'nfc_west', 'nfc', 2, 'sofi_stadium', '5-12'),
('dolphins', 'miami', 'afc_east', 'afc', 2, 'hard_rock_stadium', '9-8'),
('vikings', 'minneapolis', 'nfc_north', 'nfc', 0, 'us_bank_stadium', '13-4'),
('patriots', 'new_england', 'afc_east', 'afc', 6, 'gillette_stadium', '8-9'),
('saints', 'new_orleans', 'nfc_south', 'nfc', 1, 'caesars_superdome', '7-10'),
('giants', 'new_york', 'nfc_east', 'nfc', 4, 'metlife_stadium', '9-6-1'),
('jets', 'new_york', 'afc_east', 'afc', 0, 'metlife_stadium', '7-10'),
('eagles', 'philadelphia', 'nfc_east', 'nfc', 1, 'lincoln_financial_field', '14-3'),
('steelers', 'pittsburgh', 'afc_north', 'afc', 6, 'heinz_field', '9-8'),
('49ers', 'san_francisco', 'nfc_west', 'nfc', 5, 'levi_stadium', '13-4'),
('seahawks', 'seattle', 'nfc_west', 'nfc', 1, 'lumen_field', '9-8'),
('buccaneers', 'tampa_bay', 'nfc_south', 'nfc', 2, 'raymond_james_stadium', '8-9'),
('titans', 'nashville', 'afc_south', 'afc', 0, 'nissan_stadium', '7-10'),
('commanders', 'washington_dc', 'nfc_east', 'nfc', 3, 'fedex_field', '8-8-1');


